params:
  model : gpt2
  max_history: 2
  no_sample : True
  max_length: 20
  device: cuda
  min_length: 1
  seed: 0
  temperature: 0.7
  top_k: 0
  top_p: 0.9

files:
  dataset_path: ${hydra:runtime.cwd}/data/situationchat_original.json
  dataset_cache: ${hydra:runtime.cwd}/situationchat_original_dataset_cache_GPT2Tokenizer
  model_checkpoint: ${hydra:runtime.cwd}/runs/Dec31_08-48-01_situation_original_gpt2

setting:
  situation: i want to exchange money.
